require_relative 'podspec_versions.rb'

platformVersion = '11.3'
platform :ios, platformVersion

install! 'cocoapods', :disable_input_output_paths => true

ENV['TRIKOT_FRAMEWORK_NAME']='TrikotFrameworkName'

target 'iosApp' do
  use_frameworks!

  properties = load_properties('../gradle.properties')

  pod 'SwiftLint'
  pod 'TrikotFrameworkName', :path => '../common'
#   pod 'Trikot.http', :path => '../../trikot.http'
  pod 'Trikot.viewmodels', :path => '../../trikot.viewmodels'
  pod 'Trikot.streams', :path => '../../trikot.streams'
  pod 'Trikot.kword', :git => 'git@github.com:mirego/trikot.kword.git', :tag => properties['trikot_kword_version'], :inhibit_warnings => true

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = platformVersion
      end
    end
  end
end
