# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  #-------------------------
  # Configuration
  #-------------------------

  mainProject = Model::Project.new(
    workspacePath: "iosApp.xcworkspace",
    projectPath: "iosApp.xcodeproj",
    infoPlistPath: "./iosApp/Info.plist",
    scheme: "iosApp",
    target: "iosApp",
    bundleIdentifier: "com.trikot.sample"
  )


  certificate = Model::Certificate.new(
    path: "#{strip_quotes(ENV["PROVISIONING_DIR"])}/#{strip_quotes(ENV["PROVISIONING_CERTIFICATE_FILE"])}",
    name: strip_quotes(ENV["PROVISIONING_NAME"]),
    password: strip_quotes(ENV["PROVISIONING_CERTIFICATE_PASSWORD"])
  )

  #-------------------------
  # Public lanes
  #-------------------------

end
